CREATE TABLE IF NOT EXISTS todo_user (
    id SERIAL PRIMARY KEY,
    title VARCHAR(225) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);